version: "3"
services:
  todo-app:
    container_name: todo-app
    image: todo-app:prod
    build:
      context: .
      target: production
      dockerfile: Dockerfile
    ports:
      - "80:80"
    env_file:
      - ".env"