version: "3"
services:
  todo-app:
    container_name: todo-app-test-unit
    image: todo-app:test-unit
    network_mode: "host"
    build:
      context: .
      target: test
      dockerfile: Dockerfile
    command: tests

    env_file:
      - ".env.test"
      