- name: Deploy ToDo app
  hosts: webservers
  remote_user: ec2-user

  tasks:
    - name: Install yum Packages
      yum:
        name:
          - git
          - python3
      become: true

    - name: Install poetry
      ansible.builtin.shell: curl -sSL https://install.python-poetry.org | python3 -
      args:
        creates: ~/.local/bin/poetry

    - name: Create To-Do app directory
      ansible.builtin.file:
        path: /opt/todoapp
        state: directory
        mode: "777"
      become: true

    - name: Clone git repo
      ansible.builtin.git:
        repo: https://github.com/TomJSoftwire/Devops-Course-Starter
        dest: /opt/todoapp
        version: main

    - name: Install dependencies
      ansible.builtin.shell: source ~/.bash_profile; cd /opt/todoapp; poetry install
