apiVersion: apps/v1
kind: Deployment
metadata:
  name: module-14
spec:
  selector:
    matchLabels:
      app: module-14
  replicas: 1
  template:
    metadata:
      labels:
        app: module-14
    spec:
      containers:
        - name: todo-app
          imagePullPolicy: Never
          image: todo-app:prod
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "900m"
              memory: "1Gi"
          env:
            - name: FLASK_APP
              value: "todo_app/app"
            - name: FLASK_ENV
              value: "development"
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: todo-secrets
                  optional: true
                  key: secret-key
            - name: PORT
              value: "80"
            - name: LOG_LEVEL
              value: "INFO"
            - name: LOGGLY_TOKEN
              valueFrom:
                secretKeyRef:
                  name: todo-secrets
                  optional: true
                  key: loggly-token
            - name: MONGO_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: todo-secrets
                  optional: true
                  key: mongo-connection-string
            - name: MONGO_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: todo-secrets
                  optional: true
                  key: mongo-db-name 
            - name: OAUTH_APP_ID
              valueFrom:
                secretKeyRef:
                  name: todo-secrets
                  optional: true
                  key: oauth-app-id
            - name: OAUTH_APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: todo-secrets
                  optional: true
                  key: oauth-app-secret
            - name: ARM_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: todo-secrets
                  optional: true
                  key: arm-access-key
