apiVersion: v1
kind: Secret
metadata:
  name: todo-secrets
type: Opaque
stringData:
  secret-key: "secret-key" 
  loggly-token: "loggly-token" 
  mongo-connection-string: "mongo-connection-string" 
  mongo-db-name: "mongo-db-name" 
  oauth-app-id: "oauth-app-id" 
  oauth-app-secret: "oauth-app-secret" 
  arm-access-key: "arm-access-key" 