name: Continuous Integration
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout code"
      uses: actions/checkout@v2
    - name: "Create env file"
      run: |
        touch .env
        echo "${{ secrets.SERVER_ENV }}" > .env
    - name: "Build Docker container"
      run: docker-compose -f docker-compose-test-unit.yml build
    - name: "Unit Tests"
      run: docker-compose -f docker-compose-test-unit.yml up --exit-code-from todo-app
    - name: "End to end Tests"
      run: docker-compose -f docker-compose-test-e2e.yml up --exit-code-from todo-app

  release:
    name: Release to Production
    runs-on: ubuntu-latest
    # if: ${{ github.ref_name == 'main' }}
    # needs: test
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
    steps: 
    - name: "Checkout code"
      uses: actions/checkout@v2

    - name: "Create env file"
      run: |
        touch .env
        echo "${{ secrets.SERVER_ENV }}" > .env
    
    - name: Terraform
      run: | 
        terraform init && \
        terraform apply \
          --auto-approve \
          -var="oauth_app_id=${{ secrets.OAUTH_APP_ID }}" \
          -var="oauth_app_secret=${{ secrets.OAUTH_APP_SECRET }}" \
          -var="secret_key=${{ secrets.SECRET_KEY }}" \
          -var="env=production" \

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Docker build
      run: docker-compose -f docker-compose-prod.yml build

    - name: Tag DockerHub build
      run: docker tag todo-app:prod thomasjohnstonsoftwire/todo-app:${{ github.sha }} && docker tag todo-app:prod thomasjohnstonsoftwire/todo-app:latest

    - name: DockerHub push
      run: docker push thomasjohnstonsoftwire/todo-app:${{ github.sha }} && docker push thomasjohnstonsoftwire/todo-app:latest
    
    - name: Trigger Azure deployment
      run: curl -dH -X POST "$(terraform output -raw cd_webhook)"
