name: Continuous Integration
on: [push]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "Create env file"
      run: |
        touch .env
        echo "${{ secrets.SERVER_ENV }}" > .env
        cat .env
    - run: docker-compose -f docker-compose-test-unit.yml up
    - run: docker-compose -f docker-compose-test-e2e.yml up