name: Continuous Integration
on: [pull_request]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout code"
      uses: actions/checkout@v2
    - name: "Create env file"
      run: |
        touch .env
        echo "${{ secrets.SERVER_ENV }}" > .env
    - name: "Build Docker container"
      run: docker-compose -f docker-compose-test-unit.yml build
    - name: "Unit Tests"
      run: docker-compose -f docker-compose-test-unit.yml up --exit-code-from todo-app
    - name: "End to end Tests"
      run: docker-compose -f docker-compose-test-e2e.yml run --exit-code-from todo-app